### ISSUE TITLE
Installation Failed.

### ISSUE THREAD

**Issue by its4nas** [yoeunes/toastr#48]
When I try to install the last version of toastr I get the following error

 **Installation failed, reverting ./composer.json and ./composer.lock to their original content.**
 so I can't get the last version of toastr.

**Comment by yoeunes** [comment]
Hello Anas,

Thank you for reaching out, could you please provide the following details:

- **PHP Version**
- **Laravel Version**
- **Error Logs**: Any specific error messages that are displayed during the installation failure.
- **Screenshots**: If possible, a screenshot of the error message you're seeing could be very helpful.

**Comment by its4nas** [comment]
My PHP version is 8.2.4
I use Laravel 10
![image](https://github.com/yoeunes/toastr/assets/77188279/b2a00cac-764a-4ae6-b357-2d6fb9b524cc)

**Comment by yoeunes** [comment]
Hello Anas,

Thank you for providing the details. I wanted to inform you that `yoeunes/toastr` is now a deprecated package. It primarily serves as a means to seamlessly integrate [`PHPFlasher`](https://php-flasher.io/) into projects. The error you are encountering may be due to the fact that you are using Laravel 10, which is not compatible with the latest version of `yoeunes/toastr`.

To address this, I recommend installing version 2 of `yoeunes/toastr`, which is compatible with Laravel 10. You can do this by running the following command:

```bash
composer require yoeunes/toastr:^2.3
```

For future projects, consider directly using [`PHPFlasher`](https://php-flasher.io/), as `yoeunes/toastr` in its newer versions (v3 and above) will primarily act as a wrapper for installing `PHPFlasher`. The newer versions are compatible with Laravel v11.

If you have further questions or need additional assistance, please feel free to reach out.

Best regards,
Younes

**Comment by its4nas** [comment]
Thank you, brother, it works with version 2.3
I will try to add [PHPFlasher](https://php-flasher.io/) in the next project.

**Comment by yoeunes** [comment]
Salamou 3alaykoum Anas, i'm glad it works
